// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: protofiles/Person.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Person_Color int32

const (
	Person_None  Person_Color = 0
	Person_Black Person_Color = 1
	Person_Brown Person_Color = 2
)

// Enum value maps for Person_Color.
var (
	Person_Color_name = map[int32]string{
		0: "None",
		1: "Black",
		2: "Brown",
	}
	Person_Color_value = map[string]int32{
		"None":  0,
		"Black": 1,
		"Brown": 2,
	}
)

func (x Person_Color) Enum() *Person_Color {
	p := new(Person_Color)
	*p = x
	return p
}

func (x Person_Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Person_Color) Descriptor() protoreflect.EnumDescriptor {
	return file_protofiles_Person_proto_enumTypes[0].Descriptor()
}

func (Person_Color) Type() protoreflect.EnumType {
	return &file_protofiles_Person_proto_enumTypes[0]
}

func (x Person_Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Person_Color.Descriptor instead.
func (Person_Color) EnumDescriptor() ([]byte, []int) {
	return file_protofiles_Person_proto_rawDescGZIP(), []int{0, 0}
}

type Person struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age     int32             `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Eye     Person_Color      `protobuf:"varint,3,opt,name=eye,proto3,enum=profile.Person.Person_Color" json:"eye,omitempty"`
	Allow   *Validate         `protobuf:"bytes,4,opt,name=allow,proto3" json:"allow,omitempty"`
	Address []*Person_Address `protobuf:"bytes,5,rep,name=address,proto3" json:"address,omitempty"`
}

func (x *Person) Reset() {
	*x = Person{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_Person_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_Person_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_protofiles_Person_proto_rawDescGZIP(), []int{0}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Person) GetEye() Person_Color {
	if x != nil {
		return x.Eye
	}
	return Person_None
}

func (x *Person) GetAllow() *Validate {
	if x != nil {
		return x.Allow
	}
	return nil
}

func (x *Person) GetAddress() []*Person_Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type Validate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *Validate) Reset() {
	*x = Validate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_Person_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Validate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validate) ProtoMessage() {}

func (x *Validate) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_Person_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validate.ProtoReflect.Descriptor instead.
func (*Validate) Descriptor() ([]byte, []int) {
	return file_protofiles_Person_proto_rawDescGZIP(), []int{1}
}

func (x *Validate) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type Person_Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	City    string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
}

func (x *Person_Address) Reset() {
	*x = Person_Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_Person_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person_Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person_Address) ProtoMessage() {}

func (x *Person_Address) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_Person_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person_Address.ProtoReflect.Descriptor instead.
func (*Person_Address) Descriptor() ([]byte, []int) {
	return file_protofiles_Person_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Person_Address) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Person_Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

var File_protofiles_Person_proto protoreflect.FileDescriptor

var file_protofiles_Person_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x22, 0xaa, 0x02, 0x0a, 0x06, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x03, 0x65, 0x79,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e,
	0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x79, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x61, 0x6c,
	0x6c, 0x6f, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x05, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x38, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x1a, 0x37, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x22, 0x27, 0x0a,
	0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x42,
	0x72, 0x6f, 0x77, 0x6e, 0x10, 0x02, 0x22, 0x20, 0x0a, 0x08, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protofiles_Person_proto_rawDescOnce sync.Once
	file_protofiles_Person_proto_rawDescData = file_protofiles_Person_proto_rawDesc
)

func file_protofiles_Person_proto_rawDescGZIP() []byte {
	file_protofiles_Person_proto_rawDescOnce.Do(func() {
		file_protofiles_Person_proto_rawDescData = protoimpl.X.CompressGZIP(file_protofiles_Person_proto_rawDescData)
	})
	return file_protofiles_Person_proto_rawDescData
}

var file_protofiles_Person_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protofiles_Person_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protofiles_Person_proto_goTypes = []interface{}{
	(Person_Color)(0),      // 0: profile.Person.Person.Color
	(*Person)(nil),         // 1: profile.Person.Person
	(*Validate)(nil),       // 2: profile.Person.Validate
	(*Person_Address)(nil), // 3: profile.Person.Person.Address
}
var file_protofiles_Person_proto_depIdxs = []int32{
	0, // 0: profile.Person.Person.eye:type_name -> profile.Person.Person.Color
	2, // 1: profile.Person.Person.allow:type_name -> profile.Person.Validate
	3, // 2: profile.Person.Person.address:type_name -> profile.Person.Person.Address
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protofiles_Person_proto_init() }
func file_protofiles_Person_proto_init() {
	if File_protofiles_Person_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protofiles_Person_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_Person_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Validate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_Person_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person_Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protofiles_Person_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protofiles_Person_proto_goTypes,
		DependencyIndexes: file_protofiles_Person_proto_depIdxs,
		EnumInfos:         file_protofiles_Person_proto_enumTypes,
		MessageInfos:      file_protofiles_Person_proto_msgTypes,
	}.Build()
	File_protofiles_Person_proto = out.File
	file_protofiles_Person_proto_rawDesc = nil
	file_protofiles_Person_proto_goTypes = nil
	file_protofiles_Person_proto_depIdxs = nil
}
